-- Pop & Chill production account data.
-- Authentication remains owned by Clerk; clerk_user_id is the application identity.

create table if not exists public.user_profiles (
  clerk_user_id text primary key,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.watchlist_items (
  id bigint generated by default as identity primary key,
  clerk_user_id text not null references public.user_profiles(clerk_user_id) on delete cascade,
  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text,
  name text,
  poster_path text,
  vote_average numeric,
  release_date text,
  first_air_date text,
  created_at timestamptz not null default now(),
  unique (clerk_user_id, tmdb_id, media_type)
);

create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  clerk_user_id text not null references public.user_profiles(clerk_user_id) on delete cascade,
  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text,
  name text,
  poster_path text,
  watched_at timestamptz not null default now(),
  unique (clerk_user_id, tmdb_id, media_type)
);

create index if not exists watchlist_items_user_idx on public.watchlist_items(clerk_user_id);
create index if not exists watch_history_user_idx on public.watch_history(clerk_user_id, watched_at desc);

alter table public.user_profiles enable row level security;
alter table public.watchlist_items enable row level security;
alter table public.watch_history enable row level security;

-- Public/anonymous clients have no direct access.
-- The future authenticated API uses the server-side service role after Clerk verification.
create policy "deny anonymous profile access" on public.user_profiles for all to anon using (false) with check (false);
create policy "deny anonymous watchlist access" on public.watchlist_items for all to anon using (false) with check (false);
create policy "deny anonymous history access" on public.watch_history for all to anon using (false) with check (false);
